pull_request_title: "chore(i18n): new crowdin translations"
commit_message: "chore(i18n):"
files:
  - source: /shared/src/main/resources/locales/locale.json
    translation: /shared/src/main/resources/locales/locale_%osx_locale%.json
